# Generated by Django 4.2.2 on 2023-06-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='title',
            field=models.CharField(default='Default Title', max_length=10),
        ),
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.TextField(max_length=4096),
        ),
    ]
