# Generated by Django 4.2.2 on 2023-06-21 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_telegramuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelegramUser',
            new_name='TelegramAdmin',
        ),
    ]
