# Generated by Django 4.2.2 on 2023-06-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_telegramuser_telegramadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramadmin',
            name='title',
            field=models.CharField(default='Nickname', max_length=20),
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(default='Название', max_length=10),
        ),
    ]
